global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]
  - job_name: 'tempo'
    static_configs:
      - targets: [ 'localhost:3200' ]
  - job_name: 'webapp'
    static_configs:
      - targets: [ 'localhost:5176' ]
  - job_name: 'worker'
    static_configs:
      - targets: [ 'localhost:5295' ]
